#!/bin/env bash


python plotters/plotter_triangle_metal_comparison_Pantheon.py
python plotters/plotter_triangle_SFR_comparison_Pantheon.py
python plotters/plotter_triangle_NOsys_comparison_Pantheon.py
#python plotters/plotter_triangle_pheno_comparison_Pantheon.py

python plotters/plotter_triangle_Planck_LCDM_Pantheon.py
python plotters/plotter_triangle_Planck_wconst_Pantheon.py
python plotters/plotter_triangle_Planck_binned_Pantheon.py

python plotters/testmetal_LCDM.pyi
python plotters/testmetal_wconst.py
python plotters/testmetal_wbinned.py

python plotters/wbinned_plot_Pantheon.py
python plotters/plotter_H0_Pantheon.py
python plotters/plotter_S8_Pantheon.py

python plotters/plotter_H0_Pantheon_free.py
python plotters/plotter_S8_Pantheon_free.py
